# Generated by Django 4.0 on 2025-03-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('place_id', models.CharField(default='place_id', max_length=255, unique=True, verbose_name='ID локации')),
                ('details_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на описание')),
                ('latitude', models.DecimalField(decimal_places=14, default=-90.0, max_digits=17, verbose_name='Широта')),
                ('longtitude', models.DecimalField(decimal_places=14, default=-180.0, max_digits=18, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.PositiveIntegerField(default=1, verbose_name='Номер изображения')),
                ('img_description', models.CharField(blank=True, max_length=255, verbose_name='Описание изображения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Файл изображения')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Локация')),
            ],
            options={
                'ordering': ['location__place_name', 'img_id'],
                'unique_together': {('location', 'img_id')},
            },
        ),
    ]
