# Generated by Django 5.1.7 on 2025-03-23 19:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['img_id', 'location__place_name']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['place_id']},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='place',
            name='details_url',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=5000, verbose_name='Длинное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер изображения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID локации'),
        ),
    ]
