# Generated by Django 5.1.7 on 2025-04-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longtitude',
            field=models.DecimalField(decimal_places=14, max_digits=18, verbose_name='Долгота'),
        ),
    ]
