# Generated by Django 4.0 on 2025-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер изображения'),
        ),
    ]
