# Generated by Django 4.0 on 2025-03-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_img_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('location', 'img_id')},
        ),
    ]
