# Generated by Django 5.1.7 on 2025-03-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image',
        ),
    ]
