# Generated by Django 4.0 on 2025-03-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Длинное описание'),
        ),
    ]
