# Generated by Django 5.1.7 on 2025-04-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('ordinal', 'location')},
        ),
    ]
