# Generated by Django 4.0 on 2025-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_description',
            field=models.CharField(blank=True, max_length=30, verbose_name='Описание изображения'),
        ),
    ]
