# Generated by Django 4.0 on 2025-03-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['img_id', 'location']},
        ),
    ]
