# Generated by Django 5.1.7 on 2025-04-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
