# Generated by Django 5.1.7 on 2025-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_img_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['img_id', 'location__place_name']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['place_id']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер изображения'),
        ),
    ]
