# Generated by Django 5.1.7 on 2025-04-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
