# Generated by Django 4.0 on 2025-03-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('location', 'img_id', 'image')},
        ),
    ]
