# Generated by Django 5.1.7 on 2025-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
