# Generated by Django 4.0 on 2025-03-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('location', 'img_id')},
        ),
    ]
