# Generated by Django 5.1.7 on 2025-05-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_ordinal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['ordinal', 'location']},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
    ]
