# Generated by Django 5.1.7 on 2025-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_options_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Порядковый номер'),
        ),
    ]
